/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rbe;

import java.awt.Dimension;
import javax.swing.JFrame;
import javax.swing.JPanel;

/**
 *
 * @author YDRGZM
 */
public class CoursesPanel extends javax.swing.JPanel {

    /**
     * Creates new form Courses
     */
    public CoursesPanel(JFrame j, JPanel jp, String s) {
        initComponents();
        J = j;
        Jp = jp;
        dj = j.getPreferredSize();
        userType = s;
        
        if (userType.equals("Student")) {
            courseSemCombo.setVisible(true);
            courseNameCombo.setVisible(true);
        } else {
            courseSemBox.setVisible(true);
            courseNameBox.setVisible(true);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleBar2 = new keeptoo.KGradientPanel();
        close2 = new javax.swing.JLabel();
        maxi2 = new javax.swing.JLabel();
        mini2 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        kGradientPanel3 = new keeptoo.KGradientPanel();
        kGradientPanel5 = new keeptoo.KGradientPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        backBtn2 = new javax.swing.JButton();
        courseSemCombo = new javax.swing.JComboBox<>();
        courseNameCombo = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        courseNameBox = new javax.swing.JTextField();
        courseSemBox = new javax.swing.JTextField();

        titleBar2.setkEndColor(new java.awt.Color(108, 117, 125));
        titleBar2.setkStartColor(new java.awt.Color(33, 37, 41));
        titleBar2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                titleBar2MouseDragged(evt);
            }
        });
        titleBar2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                titleBar2MousePressed(evt);
            }
        });

        close2.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        close2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rbe/img/icons8_close_window_40px_1.png"))); // NOI18N
        close2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                close2MousePressed(evt);
            }
        });

        maxi2.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        maxi2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rbe/img/icons8_maximize_window_40px.png"))); // NOI18N
        maxi2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                maxi2MousePressed(evt);
            }
        });

        mini2.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        mini2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rbe/img/icons8_minimize_window_40px.png"))); // NOI18N
        mini2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                mini2MousePressed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Course");

        javax.swing.GroupLayout titleBar2Layout = new javax.swing.GroupLayout(titleBar2);
        titleBar2.setLayout(titleBar2Layout);
        titleBar2Layout.setHorizontalGroup(
            titleBar2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(titleBar2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(672, 672, 672)
                .addComponent(mini2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(maxi2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(close2)
                .addGap(10, 10, 10))
        );
        titleBar2Layout.setVerticalGroup(
            titleBar2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(titleBar2Layout.createSequentialGroup()
                .addGroup(titleBar2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(titleBar2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(close2)
                        .addComponent(maxi2)
                        .addComponent(mini2)))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        kGradientPanel3.setBackground(new java.awt.Color(218, 89, 34));
        kGradientPanel3.setkEndColor(new java.awt.Color(29, 9, 4));
        kGradientPanel3.setkStartColor(new java.awt.Color(133, 1, 0));
        kGradientPanel3.setPreferredSize(new java.awt.Dimension(868, 721));
        kGradientPanel3.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                kGradientPanel3MouseDragged(evt);
            }
        });
        kGradientPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                kGradientPanel3MousePressed(evt);
            }
        });

        kGradientPanel5.setkEndColor(new java.awt.Color(176, 42, 55));
        kGradientPanel5.setkStartColor(new java.awt.Color(253, 126, 20));
        kGradientPanel5.setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rbe/img/icons8_study_100px.png"))); // NOI18N
        kGradientPanel5.add(jLabel1);
        jLabel1.setBounds(17, 6, 100, 128);

        jLabel28.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setText("Semester");
        kGradientPanel5.add(jLabel28);
        jLabel28.setBounds(205, 98, 81, 29);

        jLabel29.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setText("Course");
        kGradientPanel5.add(jLabel29);
        jLabel29.setBounds(205, 165, 81, 29);

        backBtn2.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        backBtn2.setText("Back");
        backBtn2.setBorderPainted(false);
        backBtn2.setFocusPainted(false);
        backBtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtn2ActionPerformed(evt);
            }
        });
        kGradientPanel5.add(backBtn2);
        backBtn2.setBounds(17, 626, 76, 28);

        courseSemCombo.setFont(new java.awt.Font("Palatino Linotype", 1, 16)); // NOI18N
        courseSemCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Fall 2020", "Spring 2021" }));
        kGradientPanel5.add(courseSemCombo);
        courseSemCombo.setBounds(330, 100, 218, 38);

        courseNameCombo.setFont(new java.awt.Font("Palatino Linotype", 1, 16)); // NOI18N
        courseNameCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CS142 OOP", "CS100L OOP" }));
        kGradientPanel5.add(courseNameCombo);
        courseNameCombo.setBounds(330, 160, 218, 38);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        kGradientPanel5.add(jScrollPane1);
        jScrollPane1.setBounds(160, 240, 490, 230);

        courseNameBox.setFont(new java.awt.Font("Palatino Linotype", 1, 16)); // NOI18N
        courseNameBox.setToolTipText("Enter course code and course name separated by space");
        kGradientPanel5.add(courseNameBox);
        courseNameBox.setBounds(330, 160, 218, 38);

        courseSemBox.setPreferredSize(new java.awt.Dimension(64, 29));
        kGradientPanel5.add(courseSemBox);
        courseSemBox.setBounds(330, 100, 218, 38);

        javax.swing.GroupLayout kGradientPanel3Layout = new javax.swing.GroupLayout(kGradientPanel3);
        kGradientPanel3.setLayout(kGradientPanel3Layout);
        kGradientPanel3Layout.setHorizontalGroup(
            kGradientPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel3Layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(kGradientPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(53, 53, 53))
        );
        kGradientPanel3Layout.setVerticalGroup(
            kGradientPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel3Layout.createSequentialGroup()
                .addContainerGap(51, Short.MAX_VALUE)
                .addComponent(kGradientPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 567, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(titleBar2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(kGradientPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 893, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(titleBar2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(kGradientPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 680, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void close2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_close2MousePressed
        System.gc();
        System.exit(0);
    }//GEN-LAST:event_close2MousePressed

    private void maxi2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_maxi2MousePressed
        // TODO add your handling code here:
        if (J.getExtendedState() != J.MAXIMIZED_BOTH) {
            J.setExtendedState(J.MAXIMIZED_BOTH);
        } else {
            J.setExtendedState(J.NORMAL);
            J.setPreferredSize(dj);

        }
    }//GEN-LAST:event_maxi2MousePressed

    private void mini2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mini2MousePressed
        // TODO add your handling code here:
        J.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_mini2MousePressed

    private void titleBar2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_titleBar2MouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();

        J.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_titleBar2MouseDragged

    private void titleBar2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_titleBar2MousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_titleBar2MousePressed

    private void backBtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtn2ActionPerformed
        // TODO add your handling code here:
        gotoP(Jp);
    }//GEN-LAST:event_backBtn2ActionPerformed

    private void kGradientPanel3MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kGradientPanel3MouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();

        J.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_kGradientPanel3MouseDragged

    private void kGradientPanel3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kGradientPanel3MousePressed
        // TODO add your handling code here:
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_kGradientPanel3MousePressed
    public void gotoP(JPanel mp) {
        J.setContentPane(mp);
        J.revalidate();
        J.repaint();
    }
    int xMouse;
    int yMouse;

    JFrame J;
    JPanel Jp;
    Dimension dj;
    String userType;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn2;
    private javax.swing.JLabel close2;
    private javax.swing.JTextField courseNameBox;
    private javax.swing.JComboBox<String> courseNameCombo;
    private javax.swing.JTextField courseSemBox;
    private javax.swing.JComboBox<String> courseSemCombo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private keeptoo.KGradientPanel kGradientPanel3;
    private keeptoo.KGradientPanel kGradientPanel5;
    private javax.swing.JLabel maxi2;
    private javax.swing.JLabel mini2;
    private keeptoo.KGradientPanel titleBar2;
    // End of variables declaration//GEN-END:variables
}
