/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rbe;

import java.awt.Dimension;
import java.util.Date;
import javax.swing.JFrame;
import javax.swing.JPanel;

/**
 *
 * @author YDRGZM
 */
public class Profile extends javax.swing.JPanel {

    /**
     * Creates new form Profile
     */
    public Profile(JFrame j, JPanel jp, int n) {
        initComponents();
        J = j;
        dj = j.getPreferredSize();
        Jp = jp;
        lockProfile();
        hideErr();
        userIndex = n;
        viewProf();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel3 = new keeptoo.KGradientPanel();
        kGradientPanel5 = new keeptoo.KGradientPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        profNameBox = new javax.swing.JTextField();
        jCheckBox2 = new javax.swing.JCheckBox();
        profUpdateBtn = new javax.swing.JButton();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        profFNameBox = new javax.swing.JTextField();
        profEmailBox = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        profContBox = new javax.swing.JTextField();
        backBtn2 = new javax.swing.JButton();
        profEdit = new javax.swing.JCheckBox();
        profPassBox = new javax.swing.JPasswordField();
        profDOBChoose = new com.toedter.calendar.JDateChooser();
        jLabel7 = new javax.swing.JLabel();
        profNameErr = new javax.swing.JLabel();
        profFNameErr = new javax.swing.JLabel();
        profEmailErr = new javax.swing.JLabel();
        profPassErr = new javax.swing.JLabel();
        profContPhErr = new javax.swing.JLabel();
        profDobErr = new javax.swing.JLabel();
        titleBar2 = new keeptoo.KGradientPanel();
        close2 = new javax.swing.JLabel();
        maxi2 = new javax.swing.JLabel();
        mini2 = new javax.swing.JLabel();

        kGradientPanel3.setBackground(new java.awt.Color(218, 89, 34));
        kGradientPanel3.setkEndColor(new java.awt.Color(29, 9, 4));
        kGradientPanel3.setkStartColor(new java.awt.Color(133, 1, 0));
        kGradientPanel3.setPreferredSize(new java.awt.Dimension(868, 721));
        kGradientPanel3.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                kGradientPanel3MouseDragged(evt);
            }
        });
        kGradientPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                kGradientPanel3MousePressed(evt);
            }
        });

        kGradientPanel5.setkEndColor(new java.awt.Color(176, 42, 55));
        kGradientPanel5.setkStartColor(new java.awt.Color(253, 126, 20));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rbe/img/icons8_add_user_male_100px.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Name");

        jLabel10.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Password");

        profNameBox.setFont(new java.awt.Font("Palatino Linotype", 1, 16)); // NOI18N

        jCheckBox2.setBackground(new java.awt.Color(218, 89, 34));
        jCheckBox2.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        jCheckBox2.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox2.setText("Show Password");
        jCheckBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox2ActionPerformed(evt);
            }
        });

        profUpdateBtn.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        profUpdateBtn.setText("Update");
        profUpdateBtn.setBorderPainted(false);
        profUpdateBtn.setFocusPainted(false);
        profUpdateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                profUpdateBtnActionPerformed(evt);
            }
        });

        jLabel28.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setText("Father's Name");

        jLabel29.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setText("Email");

        profFNameBox.setFont(new java.awt.Font("Palatino Linotype", 1, 16)); // NOI18N

        profEmailBox.setFont(new java.awt.Font("Palatino Linotype", 1, 16)); // NOI18N

        jLabel30.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        jLabel30.setText("Contact Phone");

        profContBox.setFont(new java.awt.Font("Palatino Linotype", 1, 16)); // NOI18N

        backBtn2.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        backBtn2.setText("Back");
        backBtn2.setBorderPainted(false);
        backBtn2.setFocusPainted(false);
        backBtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtn2ActionPerformed(evt);
            }
        });

        profEdit.setBackground(new java.awt.Color(201, 69, 43));
        profEdit.setForeground(new java.awt.Color(255, 255, 255));
        profEdit.setText("EDIT Profile");
        profEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                profEditActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Date of Birth");

        profNameErr.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rbe/img/icons8_cancel_40px.png"))); // NOI18N

        profFNameErr.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rbe/img/icons8_cancel_40px.png"))); // NOI18N

        profEmailErr.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rbe/img/icons8_cancel_40px.png"))); // NOI18N

        profPassErr.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rbe/img/icons8_cancel_40px.png"))); // NOI18N

        profContPhErr.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rbe/img/icons8_cancel_40px.png"))); // NOI18N

        profDobErr.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rbe/img/icons8_cancel_40px.png"))); // NOI18N

        javax.swing.GroupLayout kGradientPanel5Layout = new javax.swing.GroupLayout(kGradientPanel5);
        kGradientPanel5.setLayout(kGradientPanel5Layout);
        kGradientPanel5Layout.setHorizontalGroup(
            kGradientPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel5Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(kGradientPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(backBtn2))
                .addGroup(kGradientPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(kGradientPanel5Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(kGradientPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(kGradientPanel5Layout.createSequentialGroup()
                                .addGroup(kGradientPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(kGradientPanel5Layout.createSequentialGroup()
                                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                                        .addGap(77, 77, 77))
                                    .addGroup(kGradientPanel5Layout.createSequentialGroup()
                                        .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(45, 45, 45))
                                    .addComponent(jLabel28, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(kGradientPanel5Layout.createSequentialGroup()
                                        .addComponent(jLabel29, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(77, 77, 77))
                                    .addGroup(kGradientPanel5Layout.createSequentialGroup()
                                        .addComponent(jLabel30, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(3, 3, 3)))
                                .addGap(11, 11, 11))
                            .addGroup(kGradientPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(87, 87, 87)))
                        .addGroup(kGradientPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(profDOBChoose, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(profPassBox, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(profContBox, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(profEmailBox, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(profFNameBox, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckBox2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(profNameBox, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(166, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel5Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(kGradientPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(profUpdateBtn)
                            .addComponent(profEdit))
                        .addGap(31, 31, 31))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(kGradientPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(profNameErr)
                    .addComponent(profFNameErr)
                    .addComponent(profEmailErr)
                    .addComponent(profPassErr)
                    .addComponent(profContPhErr)
                    .addComponent(profDobErr))
                .addGap(95, 95, 95))
        );
        kGradientPanel5Layout.setVerticalGroup(
            kGradientPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel5Layout.createSequentialGroup()
                .addGroup(kGradientPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(kGradientPanel5Layout.createSequentialGroup()
                        .addGroup(kGradientPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(kGradientPanel5Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(kGradientPanel5Layout.createSequentialGroup()
                                .addGap(64, 64, 64)
                                .addGroup(kGradientPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(kGradientPanel5Layout.createSequentialGroup()
                                        .addComponent(profEdit)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(kGradientPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(kGradientPanel5Layout.createSequentialGroup()
                                                .addGroup(kGradientPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                    .addComponent(profNameBox, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(18, 18, 18)
                                                .addGroup(kGradientPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                    .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(profFNameBox, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(kGradientPanel5Layout.createSequentialGroup()
                                                .addComponent(profNameErr, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(profFNameErr, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(18, 18, 18)
                                        .addGroup(kGradientPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(profEmailBox, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(profEmailErr, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(kGradientPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(profContBox, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(profContPhErr, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(kGradientPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(kGradientPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(profPassBox, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel5Layout.createSequentialGroup()
                                        .addComponent(profPassErr, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(8, 8, 8)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(kGradientPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(kGradientPanel5Layout.createSequentialGroup()
                                .addComponent(jCheckBox2)
                                .addGap(29, 29, 29)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(profDobErr, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(profDOBChoose, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(kGradientPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(profUpdateBtn)
                    .addComponent(backBtn2))
                .addGap(26, 26, 26))
        );

        javax.swing.GroupLayout kGradientPanel3Layout = new javax.swing.GroupLayout(kGradientPanel3);
        kGradientPanel3.setLayout(kGradientPanel3Layout);
        kGradientPanel3Layout.setHorizontalGroup(
            kGradientPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel3Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(kGradientPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(80, 80, 80))
        );
        kGradientPanel3Layout.setVerticalGroup(
            kGradientPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel3Layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(kGradientPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(115, 115, 115))
        );

        titleBar2.setkEndColor(new java.awt.Color(108, 117, 125));
        titleBar2.setkStartColor(new java.awt.Color(33, 37, 41));
        titleBar2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                titleBar2MouseDragged(evt);
            }
        });
        titleBar2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                titleBar2MousePressed(evt);
            }
        });

        close2.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        close2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rbe/img/icons8_close_window_40px_1.png"))); // NOI18N
        close2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                close2MousePressed(evt);
            }
        });

        maxi2.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        maxi2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rbe/img/icons8_maximize_window_40px.png"))); // NOI18N
        maxi2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                maxi2MousePressed(evt);
            }
        });

        mini2.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        mini2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rbe/img/icons8_minimize_window_40px.png"))); // NOI18N
        mini2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                mini2MousePressed(evt);
            }
        });

        javax.swing.GroupLayout titleBar2Layout = new javax.swing.GroupLayout(titleBar2);
        titleBar2.setLayout(titleBar2Layout);
        titleBar2Layout.setHorizontalGroup(
            titleBar2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(titleBar2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(mini2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(maxi2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(close2)
                .addGap(10, 10, 10))
        );
        titleBar2Layout.setVerticalGroup(
            titleBar2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(titleBar2Layout.createSequentialGroup()
                .addGroup(titleBar2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(close2)
                    .addComponent(maxi2)
                    .addComponent(mini2))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(titleBar2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(kGradientPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(titleBar2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(kGradientPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void kGradientPanel3MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kGradientPanel3MouseDragged
        // TODO add your handling code here:
        if (J.getExtendedState() != J.MAXIMIZED_BOTH) {
            int x = evt.getXOnScreen();
            int y = evt.getYOnScreen();

            J.setLocation(x - xMouse, y - yMouse);
        }
    }//GEN-LAST:event_kGradientPanel3MouseDragged

    private void kGradientPanel3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kGradientPanel3MousePressed
        // TODO add your handling code here:
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_kGradientPanel3MousePressed

    private void close2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_close2MousePressed
        System.gc();
        System.exit(0);
    }//GEN-LAST:event_close2MousePressed

    private void maxi2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_maxi2MousePressed
        // TODO add your handling code here:
        if (J.getExtendedState() != J.MAXIMIZED_BOTH) {
            J.setExtendedState(J.MAXIMIZED_BOTH);
        } else {
            J.setExtendedState(J.NORMAL);
            J.setPreferredSize(dj);

        }
    }//GEN-LAST:event_maxi2MousePressed

    private void mini2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mini2MousePressed
        // TODO add your handling code here:
        J.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_mini2MousePressed

    private void titleBar2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_titleBar2MouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();

        J.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_titleBar2MouseDragged

    private void titleBar2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_titleBar2MousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_titleBar2MousePressed

    private void profUpdateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profUpdateBtnActionPerformed
        // TODO add your handling code here:
        Person p = RBE.getInstance().getPersonList().get(userIndex);
        String name = profNameBox.getText();
        String fname = profFNameBox.getText();
        String email = profEmailBox.getText();
        String contPhone = profContBox.getText();
        String pass = new String(profPassBox.getPassword());
        Date date = profDOBChoose.getDate();
        int count = 0;
        if (Validator.getInstance().isValidStr(name)) {
            profNameErr.setVisible(false);
            count++;
        } else {
            profNameErr.setVisible(true);
        }
        if (Validator.getInstance().isValidStr(fname)) {
            profFNameErr.setVisible(false);
            count++;
        } else {
            profFNameErr.setVisible(true);
        }
        if (Validator.getInstance().isValidEmail(email)) {
            profEmailErr.setVisible(false);
            count++;
        } else {
            profEmailErr.setVisible(true);
        }
        if (Validator.getInstance().isValidContPhone(contPhone)) {
            profContPhErr.setVisible(false);
            count++;
        } else {
            profContPhErr.setVisible(true);
        }
        if (Validator.getInstance().isValidPwd(pass)) {
            profPassErr.setVisible(false);
            count++;
        } else {
            profPassErr.setVisible(true);
        }
        if (p.getType().equals("Student")) {
            if (date == null) {
                profDobErr.setVisible(true);
            } else {
                count++;
                profDobErr.setVisible(false);
            }
        }
        if (p.getType().equals("Teacher")) {
            if (count == 5) {
                Teacher t = new Teacher();
                t.setName(name);
                t.setFatherName(fname);
                t.setContPhone(contPhone);
                t.setEmail(email);
                t.setPassword(pass);
                RBE.getInstance().setAtIndList(userIndex, t);
                PromptMessage pt = new PromptMessage("Successfull! Account has been created", J, Jp);
                pt.setVisible(true);
            }
        } else if (p.getType().equals("Student")) {
            if (count == 6) {
                Student st = new Student();
                st.setName(name);
                st.setFatherName(fname);
                st.setDob(date);
                st.setRegNo(contPhone);
                st.setPassword(pass);
                st.setEmail(email);
                RBE.getInstance().setAtIndList(userIndex, st);
                PromptMessage pt = new PromptMessage("Successful! Details has been updated", J, Jp);
                pt.setVisible(true);

            }
        }
    }//GEN-LAST:event_profUpdateBtnActionPerformed

    private void backBtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtn2ActionPerformed
        // TODO add your handling code here:
        gotoP(Jp);

    }//GEN-LAST:event_backBtn2ActionPerformed

    private void profEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profEditActionPerformed
        // TODO add your handling code here:
        if (profEdit.isSelected()) {
            unlockProfile();
        } else {
            lockProfile();
        }
    }//GEN-LAST:event_profEditActionPerformed

    private void jCheckBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox2ActionPerformed
        // TODO add your handling code here:
        if (jCheckBox2.isSelected()) {
            profPassBox.setEchoChar((char) 0);
        } else {
            profPassBox.setEchoChar('*');
        }
    }//GEN-LAST:event_jCheckBox2ActionPerformed

    public void lockProfile() {
        profContBox.setEnabled(false);
        profEmailBox.setEnabled(false);
        profFNameBox.setEnabled(false);
        profNameBox.setEnabled(false);
        profPassBox.setEnabled(false);
    }

    public void unlockProfile() {
        profContBox.setEnabled(true);
        profEmailBox.setEnabled(true);
        profFNameBox.setEnabled(true);
        profNameBox.setEnabled(true);
        profPassBox.setEnabled(true);
    }

    private void viewProf() {
        if (RBE.getInstance().getPersonList().get(userIndex).getType().equals("Student")) {
            Student st = (Student) RBE.getInstance().getPersonList().get(userIndex);
            profNameBox.setText(st.getName());
            profFNameBox.setText(st.getFatherName());
            profPassBox.setText(st.getPassword());
            jLabel30.setText("Reg No");
            profContBox.setText(st.getRegNo());
            profEmailBox.setText(st.getEmail());
            profDOBChoose.setDate(st.getDOB());

        } else if (RBE.getInstance().getPersonList().get(userIndex).getType().equals("Teacher")) {
            Teacher t = (Teacher) RBE.getInstance().getPersonList().get(userIndex);
            jLabel7.setVisible(false);
            profDOBChoose.setVisible(false);
            profNameBox.setText(t.getName());
            profFNameBox.setText(t.getFatherName());
            profPassBox.setText(t.getPassword());
            jLabel30.setText("Contact Phone");
            profContBox.setText(t.getContPhone());
            profEmailBox.setText(t.getEmail());

        }
    }

    public void hideErr() {
        profContPhErr.setVisible(false);
        profEmailErr.setVisible(false);
        profFNameErr.setVisible(false);
        profNameErr.setVisible(false);
        profPassErr.setVisible(false);
        profDobErr.setVisible(false);
    }

    public void gotoP(JPanel mp) {
        J.setContentPane(mp);
        J.revalidate();
        J.repaint();
    }

    int xMouse;
    int yMouse;

    JFrame J;
    JPanel Jp;
    Dimension dj;
    int userIndex;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JButton backBtn2;
    private javax.swing.JLabel close;
    private javax.swing.JLabel close1;
    private javax.swing.JLabel close2;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private keeptoo.KGradientPanel kGradientPanel2;
    private keeptoo.KGradientPanel kGradientPanel3;
    private keeptoo.KGradientPanel kGradientPanel5;
    private javax.swing.JLabel maxi;
    private javax.swing.JLabel maxi1;
    private javax.swing.JLabel maxi2;
    private javax.swing.JLabel mini;
    private javax.swing.JLabel mini1;
    private javax.swing.JLabel mini2;
    private javax.swing.JTextField profContBox;
    private javax.swing.JLabel profContPhErr;
    private com.toedter.calendar.JDateChooser profDOBChoose;
    private javax.swing.JLabel profDobErr;
    private javax.swing.JCheckBox profEdit;
    private javax.swing.JTextField profEmailBox;
    private javax.swing.JLabel profEmailErr;
    private javax.swing.JTextField profFNameBox;
    private javax.swing.JLabel profFNameErr;
    private javax.swing.JTextField profNameBox;
    private javax.swing.JLabel profNameErr;
    private javax.swing.JPasswordField profPassBox;
    private javax.swing.JLabel profPassErr;
    private javax.swing.JButton profUpdateBtn;
    private javax.swing.JButton signUpBtn;
    private keeptoo.KGradientPanel titleBar;
    private keeptoo.KGradientPanel titleBar1;
    private keeptoo.KGradientPanel titleBar2;
    // End of variables declaration//GEN-END:variables
}
